version: "3.9"

services:
  mongo:
    image: "mongo"
    container_name: mongodb
    volumes:
      - "mongodata:/data/db" 
    ports:
      - '27017:27017'
  web:
    container_name: restserver
    build: .
    ports:
      - '8081:8081'
    links:
      - "mongo"
    depends_on:
      - mongo

volumes:
  mongodata:


