version: "3"

services:
  mongodb-service:
    image: "mongo"
    hostname: "mongodb"
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - "mongodata:/data/db" 
    ports:
      - 27017:27017
    depends_on:
      - mongo

  server-users:
    container_name: server-users
    build: webUsers/.
    ports:
      - 8081:8081
    depends_on:
      - mongo
    restart: unless-stopped
  
  server-subscriptions:
    container_name: server-subscriptions
    build: webSubscriptions/.
    ports:
      - 8082:8082
    depends_on:
      - mongo
    restart: unless-stopped


volumes:
  mongodata:


